(function(){var t,aa=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var u=ca(this);function v(a,b){if(b)a:{var c=u;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
var da=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if(typeof Reflect!="undefined"&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){e===void 0&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}(),ea;
if(typeof Object.setPrototypeOf=="function")ea=Object.setPrototypeOf;else{var fa;a:{var ha={a:!0},ia={};try{ia.__proto__=ha;fa=ia.a;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=ea;
function x(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.sa=b.prototype}function ma(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function y(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ma(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function A(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function oa(){this.l=!1;this.h=null;this.m=void 0;this.g=1;this.u=0;this.j=null}function pa(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}oa.prototype.o=function(a){this.m=a};
function qa(a,b){a.j={la:b,na:!0};a.g=a.u}oa.prototype.return=function(a){this.j={return:a};this.g=this.u};function ra(a){this.g=new oa;this.h=a}function sa(a,b){pa(a.g);var c=a.g.h;if(c)return ta(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return ua(a)}
function ta(a,b,c,d){try{var e=b.call(a.g.h,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.l=!1,e;var h=e.value}catch(f){return a.g.h=null,qa(a.g,f),ua(a)}a.g.h=null;d.call(a.g,h);return ua(a)}function ua(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(c){a.g.m=void 0,qa(a.g,c)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.na)throw b.la;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function va(a){this.next=function(b){pa(a.g);a.g.h?b=ta(a,a.g.h.next,b,a.g.o):(a.g.o(b),b=ua(a));return b};this.throw=function(b){pa(a.g);a.g.h?b=ta(a,a.g.h["throw"],b,a.g.o):(qa(a.g,b),b=ua(a));return b};this.return=function(b){return sa(a,b)};this[Symbol.iterator]=function(){return this}}function wa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}new Promise(function(d,e){function h(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(h,e)}h(a.next())})}
function xa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}v("Reflect",function(a){return a?a:{}});v("Reflect.construct",function(){return da});v("Reflect.setPrototypeOf",function(a){return a?a:ka?function(b,c){try{return ka(b,c),!0}catch(d){return!1}}:null});
v("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+e++,h)}function c(h,f){this.g=h;ba(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
v("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ya(ma(this))}});return a});function ya(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
v("Promise",function(a){function b(f){this.h=0;this.j=void 0;this.g=[];this.u=!1;var g=this.l();try{f(g.resolve,g.reject)}catch(k){g.reject(k)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(g){g(f)})}if(a)return a;c.prototype.h=function(f){if(this.g==null){this.g=[];var g=this;this.j(function(){g.m()})}this.g.push(f)};var e=u.setTimeout;c.prototype.j=function(f){e(f,0)};c.prototype.m=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var g=0;g<f.length;++g){var k=
f[g];f[g]=null;try{k()}catch(l){this.l(l)}}}this.g=null};c.prototype.l=function(f){this.j(function(){throw f;})};b.prototype.l=function(){function f(l){return function(m){k||(k=!0,l.call(g,m))}}var g=this,k=!1;return{resolve:f(this.G),reject:f(this.m)}};b.prototype.G=function(f){if(f===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.L(f);else{a:switch(typeof f){case "object":var g=f!=null;break a;case "function":g=!0;break a;default:g=!1}g?this.F(f):this.o(f)}};
b.prototype.F=function(f){var g=void 0;try{g=f.then}catch(k){this.m(k);return}typeof g=="function"?this.M(g,f):this.o(f)};b.prototype.m=function(f){this.C(2,f)};b.prototype.o=function(f){this.C(1,f)};b.prototype.C=function(f,g){if(this.h!=0)throw Error("Cannot settle("+f+", "+g+"): Promise already settled in state"+this.h);this.h=f;this.j=g;this.h===2&&this.H();this.K()};b.prototype.H=function(){var f=this;e(function(){if(f.D()){var g=u.console;typeof g!=="undefined"&&g.error(f.j)}},1)};b.prototype.D=
function(){if(this.u)return!1;var f=u.CustomEvent,g=u.Event,k=u.dispatchEvent;if(typeof k==="undefined")return!0;typeof f==="function"?f=new f("unhandledrejection",{cancelable:!0}):typeof g==="function"?f=new g("unhandledrejection",{cancelable:!0}):(f=u.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.j;return k(f)};b.prototype.K=function(){if(this.g!=null){for(var f=0;f<this.g.length;++f)h.h(this.g[f]);this.g=null}};var h=new c;b.prototype.L=
function(f){var g=this.l();f.N(g.resolve,g.reject)};b.prototype.M=function(f,g){var k=this.l();try{f.call(g,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(f,g){function k(p,q){return typeof p=="function"?function(r){try{l(p(r))}catch(w){m(w)}}:q}var l,m,n=new b(function(p,q){l=p;m=q});this.N(k(f,l),k(g,m));return n};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.N=function(f,g){function k(){switch(l.h){case 1:f(l.j);break;case 2:g(l.j);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;this.g==null?h.h(k):this.g.push(k);this.u=!0};b.resolve=d;b.reject=function(f){return new b(function(g,k){k(f)})};b.race=function(f){return new b(function(g,k){for(var l=y(f),m=l.next();!m.done;m=l.next())d(m.value).N(g,k)})};b.all=function(f){var g=y(f),k=g.next();return k.done?d([]):new b(function(l,m){function n(r){return function(w){p[r]=w;q--;q==0&&l(p)}}var p=[],q=0;do p.push(void 0),q++,d(k.value).N(n(p.length-1),m),k=g.next();while(!k.done)})};return b});
v("Object.setPrototypeOf",function(a){return a||ka});function za(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}v("Array.prototype.keys",function(a){return a?a:function(){return za(this,function(b){return b})}});
v("WeakMap",function(a){function b(k){this.g=(g+=Math.random()+1).toString();if(k){k=y(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function e(k){if(!A(k,f)){var l=new c;ba(k,f,{value:l})}}function h(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(m.get(k)!=2||m.get(l)!=3)return!1;m.delete(k);m.set(l,4);return!m.has(k)&&m.get(l)==4}catch(n){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var g=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!A(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&A(k,f)?k[f][this.g]:void 0};b.prototype.has=function(k){return d(k)&&A(k,
f)&&A(k[f],this.g)};b.prototype.delete=function(k){return d(k)&&A(k,f)&&A(k[f],this.g)?delete k[f][this.g]:!1};return b});
v("Map",function(a){function b(){var g={};return g.v=g.next=g.head=g}function c(g,k){var l=g[1];return ya(function(){if(l){for(;l.head!=g[1];)l=l.v;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(g,k){var l=k&&typeof k;l=="object"||l=="function"?h.has(k)?l=h.get(k):(l=""+ ++f,h.set(k,l)):l="p_"+k;var m=g[0][l];if(m&&A(g[0],l))for(g=0;g<m.length;g++){var n=m[g];if(k!==k&&n.key!==n.key||k===n.key)return{id:l,list:m,index:g,entry:n}}return{id:l,
list:m,index:-1,entry:void 0}}function e(g){this[0]={};this[1]=b();this.size=0;if(g){g=y(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),k=new a(y([[g,"s"]]));if(k.get(g)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=g||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(n){return!1}}())return a;var h=new WeakMap;e.prototype.set=function(g,k){g=g===0?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this[1],v:this[1].v,head:this[1],key:g,value:k},l.list.push(l.entry),this[1].v.next=l.entry,this[1].v=l.entry,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.entry.v.next=g.entry.next,
g.entry.next.v=g.entry.v,g.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].v=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).entry};e.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,function(g){return g.value})};e.prototype.forEach=
function(g,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,g.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});function Aa(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
v("Array.prototype.entries",function(a){return a?a:function(){return za(this,function(b,c){return[b,c]})}});v("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)A(b,d)&&c.push([d,b[d]]);return c}});v("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)A(b,d)&&c.push(b[d]);return c}});v("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});
v("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var h=d[c];if(h===b||Object.is(h,b))return!0}return!1}});v("String.prototype.includes",function(a){return a?a:function(b,c){return Aa(this,b,"includes").indexOf(b,c||0)!==-1}});
v("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(g){return g};var e=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h=="function"){b=h.call(b);for(var f=0;!(h=b.next()).done;)e.push(c.call(d,h.value,f++))}else for(h=b.length,f=0;f<h;f++)e.push(c.call(d,b[f],f));return e}});v("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});v("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});
v("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});v("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});v("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
v("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=Aa(this,b,"startsWith"),e=d.length,h=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var f=0;f<h&&c<e;)if(d[c++]!=b[f++])return!1;return f>=h}});v("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});v("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});
v("Array.prototype.values",function(a){return a?a:function(){return za(this,function(b,c){return c})}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var B=this||self;function Ba(a){var b=xa.apply(1,arguments).filter(Boolean).join("&");if(!b)return a;var c=a.match(/[?&]adurl=/);return c?a.slice(0,c.index+1)+b+"&"+a.slice(c.index+1):a+(a.indexOf("?")<0?"?":"&")+b}function Ca(a,b){return a===0?"ri=1":a===1?b?"ri=24":"ri=27":a===2?b?"ri=25":"ri=26":""}function Da(a,b){return b?"&"+a+"="+encodeURIComponent(b):""}
function Ea(a){var b=a.url;a=a.pa;this.h=b;this.l=a;this.j=(new Date).getTime()-17040672E5;this.g={};for(var c=/[?&]([^&=]+)=([^&]*)/g;a=c.exec(b);)this.g[a[1]]=a[2]}function Fa(a,b){if(a.g.dsh==="1")return null;var c=a.g.ae;if(c==="1"){var d=a.g.adurl;if(d)try{return{version:3,O:decodeURIComponent(d),I:Ba(a.h,"act=1",Ca(b,!0),Ga(a))}}catch(e){}}return c==="2"?{version:4,O:Ba(a.h,"dct=1","suid="+a.j,Ca(b,!1)),I:Ba(a.h,"act=1",Ca(b,!0),"suid="+a.j)}:null}
function Ha(a,b){return b===2?Ba(a.h,"ri=2"):b===0?Ba(a.h,"ri=16"):a.h}function Ga(a){a=a.l;if(!a)return"";var b=Da("uap",a.platform)+Da("uapv",a.platformVersion)+Da("uafv",a.uaFullVersion)+Da("uaa",a.architecture)+Da("uam",a.model)+Da("uab",a.bitness);a.fullVersionList&&(b+="&uafvl="+encodeURIComponent(a.fullVersionList.map(function(c){return encodeURIComponent(c.brand)+";"+encodeURIComponent(c.version)}).join("|")));a.wow64!=null&&(b+="&uaw="+Number(a.wow64));return b.slice(1)};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function C(a){this.g=a}C.prototype.toString=function(){return this.g};var Ia=new C("about:invalid#zClosurez");function Ja(a){this.oa=a}function D(a){return new Ja(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})}var Ka=new Ja(function(a){return/^[^:]*([/?#]|$)/.test(a)}),La=D("http"),Ma=D("https"),Na=D("ftp"),Oa=D("mailto"),Pa=D("intent"),Qa=D("market"),Ra=D("itms"),Sa=D("itms-appss"),Ta=[D("data"),La,Ma,Oa,Na,Ka],Ua=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function Va(a,b){if(b instanceof C)if(b instanceof C)b=b.g;else throw Error("");else b=Ua.test(b)?b:void 0;b!==void 0&&(a.href=b)};var Wa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Xa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function Ya(a,b){a:{for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return b<0?null:typeof a==="string"?a.charAt(b):a[b]};function Za(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b};function $a(a){B.setTimeout(function(){throw a;},0)};function ab(a){var b;a:{if(b=B.navigator)if(b=b.userAgent)break a;b=""}return b.indexOf(a)!=-1};var bb,cb;a:{for(var db=["CLOSURE_FLAGS"],eb=B,fb=0;fb<db.length;fb++)if(eb=eb[db[fb]],eb==null){cb=null;break a}cb=eb}var gb=cb&&cb[748402147];bb=gb!=null?gb:!0;function ib(){return ab("iPhone")&&!ab("iPod")&&!ab("iPad")};function jb(a){jb[" "](a);return a}jb[" "]=function(){};var kb=ib(),lb=ab("iPad");var nb=ib()||ab("iPod"),ob=ab("iPad");var pb={},qb=null;var rb=void 0;function sb(a){a=Error(a);Za(a,"warning");return a};var tb=typeof Symbol==="function"&&typeof Symbol()==="symbol";function ub(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var vb=ub("jas",void 0,!0),wb=ub(void 0,"0di"),xb=ub(void 0,"0actk"),yb=ub("m_m","ra",!0);var zb={ma:{value:0,configurable:!0,writable:!0,enumerable:!1}},Ab=Object.defineProperties,E=tb?vb:"ma",Bb,Cb=[];F(Cb,7);Bb=Object.freeze(Cb);function Db(a,b){tb||E in a||Ab(a,zb);a[E]|=b}function F(a,b){tb||E in a||Ab(a,zb);a[E]=b}function Eb(a){Db(a,34);return a}function Fb(a){Db(a,8192);return a};function Gb(){return typeof BigInt==="function"};var Hb={};function G(a,b){return b===void 0?a.g!==Ib&&!!(2&(a.i[E]|0)):!!(2&b)&&a.g!==Ib}var Ib={};function Jb(a,b,c){this.g=a;this.h=b;this.j=c}Jb.prototype.next=function(){var a=this.g.next();a.done||(a.value=this.h.call(this.j,a.value));return a};Jb.prototype[Symbol.iterator]=function(){return this};var Kb=Object.freeze({});function Lb(a){a.qa=!0;return a};var Mb=Lb(function(a){return typeof a==="number"}),Nb=Lb(function(a){return typeof a==="string"}),Ob=Lb(function(a){return typeof a==="boolean"});var Pb=typeof B.BigInt==="function"&&typeof B.BigInt(0)==="bigint";function H(a){var b=a;if(Nb(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if(Mb(b)&&!Number.isSafeInteger(b))throw Error(String(b));return Pb?BigInt(a):a=Ob(a)?a?"1":"0":Nb(a)?a.trim()||"0":String(a)}var Vb=Lb(function(a){return Pb?a>=Qb&&a<=Rb:a[0]==="-"?Sb(a,Tb):Sb(a,Ub)}),Tb=Number.MIN_SAFE_INTEGER.toString(),Qb=Pb?BigInt(Number.MIN_SAFE_INTEGER):void 0,Ub=Number.MAX_SAFE_INTEGER.toString(),Rb=Pb?BigInt(Number.MAX_SAFE_INTEGER):void 0;
function Sb(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var I=0,J=0;function Wb(a){var b=a>>>0;I=b;J=(a-b)/4294967296>>>0}function Xb(a){if(a<0){Wb(-a);var b=y(Yb(I,J));a=b.next().value;b=b.next().value;I=a>>>0;J=b>>>0}else Wb(a)}function Zb(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else Gb()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+$b(c)+$b(a));return c}
function $b(a){a=String(a);return"0000000".slice(a.length)+a}function ac(){var a=I,b=J;b&2147483648?Gb()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=y(Yb(a,b)),a=b.next().value,b=b.next().value,a="-"+Zb(a,b)):a=Zb(a,b);return a}function Yb(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function bc(a){return Array.prototype.slice.call(a)};var cc=typeof BigInt==="function"?BigInt.asIntN:void 0,dc=Number.isSafeInteger,ec=Number.isFinite,fc=Math.trunc,hc=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function ic(a){switch(typeof a){case "bigint":return!0;case "number":return ec(a);case "string":return hc.test(a);default:return!1}}function jc(a){if(!ec(a))throw sb("enum");return a|0}function kc(a){return a==null?a:ec(a)?a|0:void 0}
function lc(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return ec(a)?a|0:void 0}
function mc(a){var b=0;b=b===void 0?0:b;if(!ic(a))throw sb("int64");var c=typeof a;switch(b){case 512:switch(c){case "string":return nc(a);case "bigint":return String(cc(64,a));default:return oc(a)}case 1024:switch(c){case "string":return b=fc(Number(a)),dc(b)?a=H(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),a=Gb()?H(cc(64,BigInt(a))):H(pc(a))),a;case "bigint":return H(cc(64,a));default:return dc(a)?H(qc(a)):H(oc(a))}case 0:switch(c){case "string":return nc(a);case "bigint":return H(cc(64,a));
default:return qc(a)}default:throw Error("Unknown format requested type for int64");}}
function pc(a){var b=a.length;if(a[0]==="-"?b<20||b===20&&a<="-9223372036854775808":b<19||b===19&&a<="9223372036854775807")return a;if(a.length<16)Xb(Number(a));else if(Gb())a=BigInt(a),I=Number(a&BigInt(4294967295))>>>0,J=Number(a>>BigInt(32)&BigInt(4294967295));else{b=+(a[0]==="-");J=I=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),J*=1E6,I=I*1E6+d,I>=4294967296&&(J+=Math.trunc(I/4294967296),J>>>=0,I>>>=0);b&&(b=y(Yb(I,J)),a=b.next().value,b=b.next().value,I=a,J=b)}return ac()}
function qc(a){a=fc(a);if(!dc(a)){Xb(a);var b=I,c=J;if(a=c&2147483648)b=~b+1>>>0,c=~c>>>0,b==0&&(c=c+1>>>0);var d=c*4294967296+(b>>>0);b=Number.isSafeInteger(d)?d:Zb(b,c);a=typeof b==="number"?a?-b:b:a?"-"+b:b}return a}function oc(a){a=fc(a);dc(a)?a=String(a):(Xb(a),a=ac());return a}function nc(a){var b=fc(Number(a));if(dc(b))return String(b);b=a.indexOf(".");b!==-1&&(a=a.substring(0,b));return pc(a)}function K(a){return a==null||typeof a==="string"?a:void 0}
function uc(a,b,c,d){if(a!=null&&a[yb]===Hb)return a;if(!Array.isArray(a))return c?d&2?((a=b[wb])||(a=new b,Eb(a.i),a=b[wb]=a),b=a):b=new b:b=void 0,b;c=a[E]|0;d=c|d&32|d&2;d!==c&&F(a,d);return new b(a)}function vc(a,b,c){if(b){if(typeof a!=="string")throw Error();return a}var d;return(d=K(a))!=null?d:c?"":void 0};function wc(a){return a};var xc={},yc=function(){try{var a=function(){return da(Map,[],this.constructor)};x(a,Map);jb(new a);return!1}catch(b){return!0}}();function zc(){this.g=new Map}t=zc.prototype;t.get=function(a){return this.g.get(a)};t.set=function(a,b){this.g.set(a,b);this.size=this.g.size;return this};t.delete=function(a){a=this.g.delete(a);this.size=this.g.size;return a};t.clear=function(){this.g.clear();this.size=this.g.size};t.has=function(a){return this.g.has(a)};t.entries=function(){return this.g.entries()};
t.keys=function(){return this.g.keys()};t.values=function(){return this.g.values()};t.forEach=function(a,b){return this.g.forEach(a,b)};zc.prototype[Symbol.iterator]=function(){return this.entries()};var L=function(){function a(){return da(Map,[],this.constructor)}if(yc)return Object.setPrototypeOf(zc.prototype,Map.prototype),Object.defineProperties(zc.prototype,{size:{value:0,configurable:!0,enumerable:!0,writable:!0}}),zc;x(a,Map);return a}();function Ac(a){return a}
function M(a,b,c,d){c=c===void 0?Ac:c;d=d===void 0?Ac:d;var e=L.call(this)||this;e.B=a[E]|0;e.A=b;e.P=c;e.ba=e.A?Bc:d;for(var h=0;h<a.length;h++){var f=a[h],g=c(f[0],!1,!0),k=f[1];b?k===void 0&&(k=null):k=d(f[1],!1,!0,void 0,void 0,e.B);L.prototype.set.call(e,g,k)}return e}x(M,L);function Cc(a){if(a.B&2)throw Error("Cannot mutate an immutable Map");}function Dc(a,b){return Fb(Array.from(L.prototype.entries.call(a),b))}t=M.prototype;t.clear=function(){Cc(this);L.prototype.clear.call(this)};
t.delete=function(a){Cc(this);return L.prototype.delete.call(this,this.P(a,!0,!1))};t.entries=function(){if(this.A){var a=L.prototype.keys.call(this);a=new Jb(a,Ec,this)}else a=L.prototype.entries.call(this);return a};t.values=function(){if(this.A){var a=L.prototype.keys.call(this);a=new Jb(a,M.prototype.get,this)}else a=L.prototype.values.call(this);return a};t.forEach=function(a,b){this.A?L.prototype.forEach.call(this,function(c,d,e){a.call(b,e.get(d),d,e)}):L.prototype.forEach.call(this,a,b)};
t.set=function(a,b){Cc(this);a=this.P(a,!0,!1);return a==null?this:b==null?(L.prototype.delete.call(this,a),this):L.prototype.set.call(this,a,this.ba(b,!0,!0,this.A,!1,this.B))};t.has=function(a){return L.prototype.has.call(this,this.P(a,!1,!1))};t.get=function(a){a=this.P(a,!1,!1);var b=L.prototype.get.call(this,a);if(b!==void 0){var c=this.A;return c?(c=this.ba(b,!1,!0,c,this.ka,this.B),c!==b&&L.prototype.set.call(this,a,c),c):b}};M.prototype[Symbol.iterator]=function(){return this.entries()};
M.prototype.toJSON=void 0;function Bc(a,b,c,d,e,h){a=uc(a,d,c,h);e&&(a=Fc(a));return a}function Ec(a){return[a,this.get(a)]}var Gc;function Hc(){return Gc||(Gc=new M(Eb([]),void 0,void 0,void 0,xc))};function Ic(a,b,c,d){var e=d!==void 0;d=!!d;var h=[],f=a.length,g=4294967295,k=!1,l=!!(b&64),m=l?b&128?0:-1:void 0;if(!(b&1)){var n=f&&a[f-1];n!=null&&typeof n==="object"&&n.constructor===Object?(f--,g=f):n=void 0;if(l&&!(b&128)&&!e){k=!0;var p;g=((p=Jc)!=null?p:wc)(g-m,m,a,n,void 0)+m}}b=void 0;for(e=0;e<f;e++)if(p=a[e],p!=null&&(p=c(p,d))!=null)if(l&&e>=g){var q=e-m,r=void 0;((r=b)!=null?r:b={})[q]=p}else h[e]=p;if(n)for(var w in n)a=n[w],a!=null&&(a=c(a,d))!=null&&(f=+w,e=void 0,l&&!Number.isNaN(f)&&
(e=f+m)<g?h[e]=a:(f=void 0,((f=b)!=null?f:b={})[w]=a));b&&(k?h.push(b):h[g]=b);return h}function Kc(a){a[0]=Lc(a[0]);a[1]=Lc(a[1]);return a}function Lc(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return Vb(a)?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[E]|0;return a.length===0&&b&1?void 0:Ic(a,b,Lc)}if(a!=null&&a[yb]===Hb)return Mc(a);if(a instanceof M)return a=a.size!==0?Dc(a,Kc):void 0,a;return}return a}var Jc;
function Mc(a){a=a.i;return Ic(a,a[E]|0,Lc)};function N(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");e=a[E]|0;if(bb&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&Nc();if(e&256)throw Error("farr");if(e&64)return(e|d)!==e&&F(a,e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var h=c.length;if(h){var f=h-1,g=c[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){b=e&128?0:-1;f-=b;if(f>=1024)throw Error("pvtlmt");for(var k in g)h=
+k,h<f&&(c[h+b]=g[k],delete g[k]);e=e&-16760833|(f&1023)<<14;break a}}if(b){k=Math.max(b,h-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-16760833|(k&1023)<<14}}}F(a,e|64|d);return a}function Nc(){if(bb)throw Error("carr");if(xb!=null){var a;var b=(a=rb)!=null?a:rb={};a=b[xb]||0;a>=5||(b[xb]=a+1,b=Error(),Za(b,"incident"),$a(b))}};function Oc(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[E]|0;return a.length===0&&c&1?void 0:Pc(a,c,b)}if(a!=null&&a[yb]===Hb)return Qc(a);if(a instanceof M){b=a.B;if(b&2)return a;if(a.size){c=Eb(Dc(a));if(a.A)for(a=0;a<c.length;a++){var d=c[a],e=d[1];e==null||typeof e!=="object"?e=void 0:e!=null&&e[yb]===Hb?e=Qc(e):Array.isArray(e)?e=Pc(e,e[E]|0,!!(b&32)):e=void 0;d[1]=e}return c}}}
function Pc(a,b,c){if(b&2)return a;!c||4096&b||16&b?a=Rc(a,b,!1,c&&!(b&16)):(Db(a,34),b&4&&Object.freeze(a));return a}function Sc(a,b,c){a=new a.constructor(b);c&&(a.g=Ib);a.h=Ib;return a}function Qc(a){var b=a.i,c=b[E]|0;return G(a,c)?a:Tc(a,b,c)?Sc(a,b):Rc(b,c)}function Uc(a){var b=a.i,c=b[E]|0;return Tc(a,b,c)?Sc(a,b,!0):new a.constructor(Rc(b,c,!1))}function Rc(a,b,c,d){d!=null||(d=!!(34&b));a=Ic(a,b,Oc,d);d=32;c&&(d|=2);b=b&16769217|d;F(a,b);return a}
function Fc(a){var b=a.i,c=b[E]|0;return G(a,c)?Tc(a,b,c)?Sc(a,b,!0):new a.constructor(Rc(b,c,!1)):a}function Vc(a){if(a.g!==Ib)return!1;var b=a.i;b=Rc(b,b[E]|0);Db(b,2048);a.i=b;a.g=void 0;a.h=void 0;return!0}function Wc(a){if(!Vc(a)&&G(a,a.i[E]|0))throw Error();}function Xc(a,b){b===void 0&&(b=a[E]|0);b&32&&!(b&4096)&&F(a,b|4096)}function Tc(a,b,c){return c&2?!0:c&32&&!(c&4096)?(F(b,c|2),a.g=Ib,!0):!1};function O(a,b){a=Yc(a.i,b);if(a!==null)return a}function Yc(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),h=a.length-1;if(!(h<1+(c?0:-1))){if(e>=h){var f=a[h];if(f!=null&&typeof f==="object"&&f.constructor===Object){c=f[b];var g=!0}else if(e===h)c=f;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return g?f[b]=d:a[e]=d,d}return c}}function Zc(a,b,c){Wc(a);var d=a.i;P(d,d[E]|0,b,c);return a}
function P(a,b,c,d){var e=c+-1,h=a.length-1;if(h>=0&&e>=h){var f=a[h];if(f!=null&&typeof f==="object"&&f.constructor===Object)return f[c]=d,b}if(e<=h)return a[e]=d,b;if(d!==void 0){var g;h=((g=b)!=null?g:b=a[E]|0)>>14&1023||536870912;c>=h?d!=null&&(e={},a[h+-1]=(e[c]=d,e)):a[e]=d}return b}function $c(a,b,c){a=a.i;return ad(a,a[E]|0,b,c)!==void 0}
function bd(a,b,c,d,e){var h=a.i,f=h[E]|0;d=G(a,f)?1:d;e=!!e||d===3;d===2&&Vc(a)&&(h=a.i,f=h[E]|0);a=cd(h,b);var g=a===Bb?7:a[E]|0,k=dd(g,f);var l=4&k?!1:!0;if(l){4&k&&(a=bc(a),g=0,k=ed(k,f),f=P(h,f,b,a));for(var m=0,n=0;m<a.length;m++){var p=c(a[m]);p!=null&&(a[n++]=p)}n<m&&(a.length=n);c=(k|4)&-513;k=c&=-1025;k&=-4097}k!==g&&(F(a,k),2&k&&Object.freeze(a));return a=fd(a,k,h,f,b,d,l,e)}
function fd(a,b,c,d,e,h,f,g){var k=b;h===1||(h!==4?0:2&b||!(16&b)&&32&d)?gd(b)||(b|=!a.length||f&&!(4096&b)||32&d&&!(4096&b||16&b)?2:256,b!==k&&F(a,b),Object.freeze(a)):(h===2&&gd(b)&&(a=bc(a),k=0,b=ed(b,d),d=P(c,d,e,a)),gd(b)||(g||(b|=16),b!==k&&F(a,b)));2&b||!(4096&b||16&b)||Xc(c,d);return a}function cd(a,b){a=Yc(a,b);return Array.isArray(a)?a:Bb}function dd(a,b){2&b&&(a|=2);return a|1}function gd(a){return!!(2&a)&&!!(4&a)||!!(256&a)}
function hd(a,b,c,d){var e=a.i,h=e[E]|0;var f=G(a,h);a:{!f&&Vc(a)&&(e=a.i,h=e[E]|0);var g=Yc(e,b);a=!1;if(g==null){if(f){b=Hc();break a}g=[]}else if(g.constructor===M)if(g.B&2&&!f)g=Dc(g);else{b=g;break a}else Array.isArray(g)?a=!!((g[E]|0)&2):g=[];if(f){if(!g.length){b=Hc();break a}a||(a=!0,Eb(g))}else if(a){a=!1;Fb(g);g=bc(g);for(var k=0;k<g.length;k++){var l=g[k]=bc(g[k]);Array.isArray(l[1])&&(l[1]=Eb(l[1]))}g=Fb(g)}!a&&h&32&&Db(g,32);d=new M(g,c,vc,d);h=P(e,h,b,d);a||Xc(e,h);b=d}!f&&c&&(b.ka=
!0);return b}function id(a,b){return hd(a,b,void 0,vc)}function ad(a,b,c,d){var e=!1;d=Yc(a,d,void 0,function(h){var f=uc(h,c,!1,b);e=f!==h&&f!=null;return f});if(d!=null)return e&&!G(d)&&Xc(a,b),d}function Q(a,b,c){var d=a.i,e=d[E]|0;b=ad(d,e,b,c);if(b==null)return b;e=d[E]|0;if(!G(a,e)){var h=Fc(b);h!==b&&(Vc(a)&&(d=a.i,e=d[E]|0),b=h,e=P(d,e,c,b),Xc(d,e))}return b}function ed(a,b){return a=(2&b?a|2:a&-3)&-273}
function R(a,b){var c=c===void 0?!1:c;a=O(a,b);a=a==null||typeof a==="boolean"?a:typeof a==="number"?!!a:void 0;return a!=null?a:c}function jd(a,b){var c=c===void 0?0:c;var d;return(d=lc(O(a,b)))!=null?d:c}function S(a,b){var c=c===void 0?"":c;var d;return(d=K(O(a,b)))!=null?d:c}function kd(a,b,c){c=c===void 0?0:c;var d;return(d=kc(O(a,b)))!=null?d:c}
function ld(a,b,c){if(c!=null&&typeof c!=="boolean")throw a=typeof c,Error("Expected boolean but got "+(a!="object"?a:c?Array.isArray(c)?"array":a:"null")+": "+c);return Zc(a,b,c)}function T(a,b,c){if(c!=null){if(typeof c!=="number")throw sb("int32");if(!ec(c))throw sb("int32");c|=0}Zc(a,b,c)}function U(a,b,c){if(c!=null&&typeof c!=="string")throw Error();return Zc(a,b,c)}function md(a,b,c){Zc(a,b,c==null?c:jc(c))};function V(a,b,c){this.i=N(a,b,c,2048)}V.prototype.toJSON=function(){return Mc(this)};function nd(a){return JSON.stringify(Mc(a))}V.prototype[yb]=Hb;V.prototype.toString=function(){return this.i.toString()};function od(a){this.i=N(a,void 0,void 0,2048)}x(od,V);function pd(a){this.i=N(a,void 0,void 0,2048)}x(pd,V);function qd(a){this.i=N(a,void 0,void 0,2048)}x(qd,V);function rd(a){this.i=N(a,void 0,void 0,2048)}x(rd,V);function sd(a){this.i=N(a,void 0,void 0,2048)}x(sd,V);function td(a){this.i=N(a,void 0,void 0,2048)}x(td,V);td.prototype.J=function(){return S(this,3)};td.prototype.aa=function(a){ld(this,5,a)};function X(a){this.i=N(a,void 0,void 0,2048)}x(X,V);X.prototype.J=function(){return S(this,1)};X.prototype.aa=function(a){ld(this,2,a)};function ud(a){this.i=N(a,void 0,void 0,2048)}x(ud,V);function vd(a){this.i=N(a,void 0,void 0,2048)}x(vd,V);function wd(a){this.i=N(a,void 0,void 0,2048)}x(wd,V);
function xd(a){var b=a.i,c=b;b=b[E]|0;var d=void 0===Kb?2:4,e=G(a,b),h=e?1:d;d=h===3;var f=!e;(h===2||f)&&Vc(a)&&(c=a.i,b=c[E]|0);a=cd(c,7);var g=a===Bb?7:a[E]|0,k=dd(g,b);if(e=!(4&k)){var l=a,m=b,n=!!(2&k);n&&(m|=2);for(var p=!n,q=!0,r=0,w=0;r<l.length;r++){var z=uc(l[r],td,!1,m);if(z instanceof td){if(!n){var la=G(z);p&&(p=!la);q&&(q=la)}l[w++]=z}}w<r&&(l.length=w);k|=4;k=q?k&-4097:k|4096;k=p?k|8:k&-9}k!==g&&(F(a,k),2&k&&Object.freeze(a));if(f&&!(8&k||!a.length&&(h===1||(h!==4?0:2&k||!(16&k)&&32&
b)))){gd(k)&&(a=bc(a),k=ed(k,b),b=P(c,b,7,a));f=a;g=k;for(l=0;l<f.length;l++)k=f[l],m=Fc(k),k!==m&&(f[l]=m);g|=8;k=g=f.length?g|4096:g&-4097;F(a,k)}return a=fd(a,k,c,b,7,h,e,d)};function yd(a){this.i=N(a,void 0,void 0,2048)}x(yd,V);function zd(a){this.i=N(a,void 0,void 0,2048)}x(zd,V);function Ad(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)};function Bd(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};function Cd(a){a=a===void 0?document:a;return a.createElement("img")};var Dd=[];function Ed(){var a=Dd;Dd=[];a=y(a);for(var b=a.next();!b.done;b=a.next()){b=b.value;try{b()}catch(c){}}}function Fd(a){Dd.push(a);Dd.length===1&&(window.Promise?Promise.resolve().then(Ed):(a=window.setImmediate,typeof a==="function"?a(Ed):setTimeout(Ed,0)))};var Gd={capture:!0},Hd={passive:!0},Id=Bd(function(){var a=!1;try{var b=Object.defineProperty({},"passive",{get:function(){a=!0}});B.addEventListener("test",null,b)}catch(c){}return a});function Jd(a){return a?a.passive&&Id()?a:a.capture||!1:!1}function Kd(a,b,c,d){typeof a.addEventListener==="function"&&a.addEventListener(b,c,Jd(d))}function Ld(a){a.preventDefault?a.preventDefault():a.returnValue=!1}
function Md(a){var b=Y;b.readyState==="complete"||b.readyState==="interactive"?Fd(a):b.addEventListener("DOMContentLoaded",a)}function Nd(a){var b=window;b.document.readyState==="complete"?Fd(a):b.addEventListener("load",a)};function Od(a,b,c,d){Pd(a,b,c===void 0?null:c,d===void 0?!1:d)}
function Pd(a,b,c,d){var e=!1;e=e===void 0?!1:e;a.google_image_requests||(a.google_image_requests=[]);var h=Cd(a.document);if(c||d){var f=function(g){c&&c(g);if(d){g=a.google_image_requests;var k=Wa(g,h);k>=0&&Array.prototype.splice.call(g,k,1)}typeof h.removeEventListener==="function"&&h.removeEventListener("load",f,Jd());typeof h.removeEventListener==="function"&&h.removeEventListener("error",f,Jd())};Kd(h,"load",f);Kd(h,"error",f)}e&&(h.attributionSrc="");h.src=b;a.google_image_requests.push(h)}
function Qd(a){var b=window;var c=c===void 0?!1:c;var d;if(d=b.navigator)d=b.navigator.userAgent,d=/Chrome/.test(d)&&!/Edge/.test(d)?!0:!1;d&&typeof b.navigator.sendBeacon==="function"?b.navigator.sendBeacon(a):Od(b,a,void 0,c)};var Rd=0;function Yd(){var a=Zd(Rd,document.currentScript);a&&(a.dataset.initialized="true")}function $d(a){return(a=Zd(a,document.currentScript))&&a.getAttribute("data-jc-version")||"unknown"}function Zd(a,b){return(b=b===void 0?null:b)&&b.getAttribute("data-jc")===String(a)?b:document.querySelector('[data-jc="'+a+'"]')}
function ae(a){var b=b===void 0?.01:b;if(!(Math.random()>b)){var c=Zd(a,document.currentScript);a="https://"+(c&&c.getAttribute("data-jc-rcd")==="true"?"pagead2.googlesyndication-cn.com":"pagead2.googlesyndication.com")+"/pagead/gen_204?id=jca&jc="+a+"&version="+$d(a)+"&sample="+b;Qd(a)}};function be(a,b){var c=c===void 0?{}:c;this.error=a;this.meta=c;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror"};function ce(a){var b=a.toString();a.name&&b.indexOf(a.name)==-1&&(b+=": "+a.name);a.message&&b.indexOf(a.message)==-1&&(b+=": "+a.message);if(a.stack)a:{a=a.stack;var c=b;try{a.indexOf(c)==-1&&(a=c+"\n"+a);for(var d;a!=d;)d=a,a=a.replace(RegExp("((https?:/..*/)[^/:]*:\\d+(?:.|\n)*)\\2"),"$1");b=a.replace(RegExp("\n *","g"),"\n");break a}catch(e){b=c;break a}b=void 0}return b};var de=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)");function ee(a,b){this.g=a;this.h=b}function fe(a,b){this.url=a;this.g=!!b;this.depth=null};var ge=null;function he(){var a=a===void 0?B:a;return(a=a.performance)&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()}function ie(){var a=a===void 0?B:a;return(a=a.performance)&&a.now?a.now():null};function je(a,b){var c=ie()||he();this.label=a;this.type=b;this.value=c;this.duration=0;this.taskId=this.slotId=void 0;this.uniqueId=Math.random()};var Z=B.performance,ke=!!(Z&&Z.mark&&Z.measure&&Z.clearMarks),le=Bd(function(){var a;if(a=ke){var b=b===void 0?window:b;if(ge===null){ge="";try{a="";try{a=b.top.location.hash}catch(d){a=b.location.hash}if(a){var c=a.match(/\bdeid=([\d,]+)/);ge=c?c[1]:""}}catch(d){}}b=ge;a=!!b.indexOf&&b.indexOf("1337")>=0}return a});
function me(){var a=window;this.h=[];this.j=a||B;var b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.h=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.g=le()||(b!=null?b:Math.random()<1)}function ne(a){a&&Z&&le()&&(Z.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),Z.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))}me.prototype.start=function(a,b){if(!this.g)return null;a=new je(a,b);b="goog_"+a.label+"_"+a.uniqueId+"_start";Z&&le()&&Z.mark(b);return a};
me.prototype.end=function(a){if(this.g&&typeof a.value==="number"){a.duration=(ie()||he())-a.value;var b="goog_"+a.label+"_"+a.uniqueId+"_end";Z&&le()&&Z.mark(b);!this.g||this.h.length>2048||this.h.push(a)}};function oe(){this.j="&";this.h={};this.l=0;this.g=[]}function pe(a,b){var c={};c[a]=b;return[c]}function qe(a,b,c,d,e){var h=[];Ad(a,function(f,g){(f=re(f,b,c,d,e))&&h.push(g+"="+f)});return h.join(b)}
function re(a,b,c,d,e){if(a==null)return"";b=b||"&";c=c||",$";typeof c==="string"&&(c=c.split(""));if(a instanceof Array){if(d||(d=0),d<c.length){for(var h=[],f=0;f<a.length;f++)h.push(re(a[f],b,c,d+1,e));return h.join(c[d])}}else if(typeof a==="object")return e||(e=0),e<2?encodeURIComponent(qe(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))}
function se(a,b,c){b="https://"+b+c;var d=te(a)-c.length;if(d<0)return"";a.g.sort(function(m,n){return m-n});c=null;for(var e="",h=0;h<a.g.length;h++)for(var f=a.g[h],g=a.h[f],k=0;k<g.length;k++){if(!d){c=c==null?f:c;break}var l=qe(g[k],a.j,",$");if(l){l=e+l;if(d>=l.length){d-=l.length;b+=l;e=a.j;break}c=c==null?f:c}}a="";c!=null&&(a=e+"trn="+c);return b+a}function te(a){var b=1,c;for(c in a.h)c.length>b&&(b=c.length);return 3997-b-a.j.length-1};var ue=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function ve(a,b){if(!b)return a;var c=a.indexOf("#");c<0&&(c=a.length);var d=a.indexOf("?");if(d<0||d>c){d=c;var e=""}else e=a.substring(d+1,c);a=[a.slice(0,d),e,a.slice(c)];c=a[1];a[1]=b?c?c+"&"+b:b:c;return a[0]+(a[1]?"?"+a[1]:"")+a[2]}
function we(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)we(a,String(b[d]),c);else b!=null&&c.push(a+(b===""?"":"="+encodeURIComponent(String(b))))}function xe(a,b,c,d){for(var e=c.length;(b=a.indexOf(c,b))>=0&&b<d;){var h=a.charCodeAt(b-1);if(h==38||h==63)if(h=a.charCodeAt(b+e),!h||h==61||h==38||h==35)return b;b+=e+1}return-1}var ye=/#|$/;
function ze(a,b){var c=a.search(ye),d=xe(a,0,b,c);if(d<0)return null;var e=a.indexOf("&",d);if(e<0||e>c)e=c;d+=b.length+1;return decodeURIComponent(a.slice(d,e!==-1?e:0).replace(/\+/g," "))}var Ae=/[?&]($|#)/;function Be(a,b){for(var c=a.search(ye),d=0,e,h=[];(e=xe(a,d,b,c))>=0;)h.push(a.substring(d,e)),d=Math.min(a.indexOf("&",e)+1||c,c);h.push(a.slice(d));return h.join("").replace(Ae,"$1")}function Ce(a,b){a=Be(a,"label");b=b!=null?"="+encodeURIComponent(String(b)):"";return ve(a,"label"+b)};function De(){var a=Ee;this.pinger=Fe;this.g=a===void 0?null:a;this.h=null;this.j=!1;this.m=this.l}function Ge(a,b){var c=He;try{if(c.g&&c.g.g){var d=c.g.start(a.toString(),3);var e=b();c.g.end(d)}else e=b()}catch(g){b=!0;try{ne(d),b=c.m(a,new be(g,{message:ce(g)}),void 0,void 0)}catch(k){c.l(217,k)}if(b){var h,f;(h=window.console)==null||(f=h.error)==null||f.call(h,g)}else throw g;}return e}
function Ie(a,b){return function(){var c=xa.apply(0,arguments);return Ge(a,function(){return b.apply(void 0,c)})}}
De.prototype.l=function(a,b,c,d,e){e=e||"jserror";var h=void 0;try{var f=new oe;f.g.push(1);f.h[1]=pe("context",a);b.error&&b.meta&&b.id||(b=new be(b,{message:ce(b)}));if(b.msg){var g=b.msg.substring(0,512);f.g.push(2);f.h[2]=pe("msg",g)}var k=b.meta||{};if(this.h)try{this.h(k)}catch(na){}if(d)try{d(k)}catch(na){}d=[k];f.g.push(3);f.h[3]=d;var l;if(!(l=z)){g=B;d=[];k=null;do{var m=g;try{var n;if(n=!!m&&m.location.href!=null)b:{try{jb(m.foo);n=!0;break b}catch(na){}n=!1}var p=n}catch(na){p=!1}if(p){var q=
m.location.href;k=m.document&&m.document.referrer||null}else q=k,k=null;d.push(new fe(q||""));try{g=m.parent}catch(na){g=null}}while(g&&m!==g);q=0;for(var r=d.length-1;q<=r;++q)d[q].depth=r-q;m=B;if(m.location&&m.location.ancestorOrigins&&m.location.ancestorOrigins.length===d.length-1)for(r=1;r<d.length;++r){var w=d[r];w.url||(w.url=m.location.ancestorOrigins[r-1]||"",w.g=!0)}l=d}var z=l;var la=new fe(B.location.href,!1);l=null;var rc=z.length-1;for(m=rc;m>=0;--m){var W=z[m];!l&&de.test(W.url)&&(l=
W);if(W.url&&!W.g){la=W;break}}W=null;var tf=z.length&&z[rc].url;la.depth!==0&&tf&&(W=z[rc]);h=new ee(la,W);if(h.h){var uf=h.h.url||"";f.g.push(4);f.h[4]=pe("top",uf)}var sc={url:h.g.url||""};if(h.g.url){var tc=h.g.url.match(ue),Sd=tc[1],Td=tc[3],Ud=tc[4];z="";Sd&&(z+=Sd+":");Td&&(z+="//",z+=Td,Ud&&(z+=":"+Ud));var Vd=z}else Vd="";sc=[sc,{url:Vd}];f.g.push(5);f.h[5]=sc;Je(this.pinger,e,f,this.j,c)}catch(na){try{var Wd,Xd;Je(this.pinger,e,{context:"ecmserr",rctx:a,msg:ce(na),url:(Xd=(Wd=h)==null?void 0:
Wd.g.url)!=null?Xd:""},this.j,c)}catch(Wf){}}return!0};function Ke(){};function Le(){this.domain="pagead2.googlesyndication.com";this.path="/pagead/gen_204?id=";this.g=Math.random()}function Me(){var a=Fe,b=window.google_srt;b>=0&&b<=1&&(a.g=b)}function Je(a,b,c,d,e){if(((d===void 0?0:d)?a.g:Math.random())<(e||.01))try{if(c instanceof oe)var h=c;else h=new oe,Ad(c,function(g,k){var l=h,m=l.l++;g=pe(k,g);l.g.push(m);l.h[m]=g});var f=se(h,a.domain,a.path+b+"&");f&&Od(B,f)}catch(g){}};var Ne=[La,Ma,Oa,Na,Ka,Qa,Ra,Pa,Sa];function Oe(a,b){if(a instanceof C)return a;var c=Ne;c=c===void 0?Ta:c;a:if(c=c===void 0?Ta:c,a instanceof C)c=a;else{for(var d=0;d<c.length;++d){var e=c[d];if(e instanceof Ja&&e.oa(a)){c=new C(a);break a}}c=void 0}c=c||Ia;c===Ia&&b(a);return c}
function Pe(a){return function(b){b={id:"unsafeurl",ctx:a,url:b};var c=[];for(d in b)we(d,b[d],c);var d=ve("https://pagead2.googlesyndication.com/pagead/gen_204",c.join("&"));navigator.sendBeacon&&navigator.sendBeacon(d,"")}};var Fe,He,Ee=new me;function Qe(){if(!window.google_measure_js_timing){var a=Ee;a.g=!1;a.h!==a.j.google_js_reporting_queue&&(le()&&Xa(a.h,ne),a.h.length=0)}}(function(a){Fe=a!=null?a:new Le;typeof window.google_srt!=="number"&&(window.google_srt=Math.random());Me();He=new De;He.h=function(b){var c=Rd;c!==0&&(b.jc=String(c),b.shv=$d(c))};He.j=!0;window.document.readyState==="complete"?Qe():Ee.g&&Kd(window,"load",function(){Qe()})})();function Re(a,b){return Ie(a,b)}
function Se(a,b){var c="Z";Ke.Z&&Ke.hasOwnProperty(c)||(c=new Ke,Ke.Z=c);c=[];!b.eid&&c.length&&(b.eid=c.toString());Je(Fe,a,b,!0)};function Te(){var a=a===void 0?B:a;return a.oneAfmaInstance};var Y=document,Ue=window;function Ve(a){var b=Y;try{return b.querySelectorAll("*["+a+"]")}catch(c){return[]}};function We(a){this.i=N(a,void 0,void 0,2048)}x(We,V);function Xe(a){var b=new We;Wc(b);b=bd(b,1,kc,2,!0);if(Array.isArray(a))for(var c=a.length,d=0;d<c;d++)b.push(jc(a[d]));else for(a=y(a),c=a.next();!c.done;c=a.next())b.push(jc(c.value))};[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2].reduce(function(a,b){return a+b});Xe([1,8,9,10,11,12,2,3,4,5,15,16,19,20,21,23]);Xe([1,6,7,9,10,11,12,2,3,4,5,13,14,18,19,20,21,23]);Xe([1,6,7,9,10,11,12,22,2,3,4,5,13,14,17,18,19,20,21,23]);new We;function Ye(a,b){b=S(a,2)||b;if(!b)return"";if(R(a,13))return b;var c=/[?&]adurl=([^&]+)/.exec(b);if(!c)return b;var d=[b.slice(0,c.index+1)];id(a,4).forEach(function(e,h){d.push(encodeURIComponent(h)+"="+encodeURIComponent(e)+"&")});d.push(b.slice(c.index+1));return R(a,27)?(b=d.join(""),(a=id(a,4).get("label"))&&(b=Ce(b,a)),b):d.join("")}
function Ze(a,b){b=b===void 0?[]:b;b=b.length>0?b:Ve("data-asoch-targets");a=hd(a,1,wd);for(var c=[],d=0;d<b.length;++d){for(var e=b[d].getAttribute("data-asoch-targets"),h=e.split(","),f=!0,g=y(h),k=g.next();!k.done;k=g.next())if(!a.has(k.value)){f=!1;break}if(f){f=a.get(h[0]);for(e=1;e<h.length;++e){g=a.get(h[e]);f=Uc(f);f=Mc(f);g=Mc(g);k=Math.max(f.length,g.length);for(var l=0;l<k;++l)f[l]==null&&(f[l]=g[l]);f=new wd(f)}h=id(f,4);kc(O(f,5))!=null&&h.set("nb",kd(f,5).toString());c.push({element:b[d],
data:f})}else Se("gdn-asoch",{type:1,data:e})}return c}
function $e(a,b,c,d,e){e=e===void 0?!1:e;c=Ye(b,c);if(c.length!==0){var h=d===609;if(ze(c,"ase")==="2"&&d!==1087){var f,g=!((f=Y.featurePolicy)==null||!f.allowedFeatures().includes("attribution-reporting"));f=h?4:g?6:5;var k="",l=Fa(new Ea({url:c}),0);e?(c=af(c,"nis",f.toString()),a.setAttribute("attributionsrc",k)):h||g&&(!l||l.version!==3)?(c=af(c,"nis",f.toString()),a.setAttribute("attributionsrc",k)):g&&l&&l.version===3&&(k=af(l.I,"nis",f.toString()),a.setAttribute("attributionsrc",k))}h&&$c(b,
od,24)&&(e=Q(b,od,24),a.setAttribute("attributionDestination",S(e,2)),a.setAttribute("attributionSourceNonce",S(e,1)));(e=(e=Zd(35))&&e.dataset.expanded?e.dataset.expanded:null)&&d===557&&(c=bf(c,"expanded",e));Va(a,Oe(c,Pe(d)));a.target||(a.target=K(O(b,11))!=null?S(b,11):"_top")}}
function cf(a){var b=b===void 0?"":b;var c=c===void 0?!1:c;a=y(a);for(var d=a.next();!d.done;d=a.next()){var e=d.value;d=e.data;var h=b.length===0?!1:e.element.matches(b);e.element.tagName!="A"||R(d,1)||h||(e=e.element,$e(e,d,e.href,c?1087:609))}}function bf(a,b,c){b=encodeURIComponent(b);var d=encodeURIComponent(c);c=new RegExp("[?&]"+b+"=([^&]+)");var e=c.exec(a);b=b+"="+d;return e?a.replace(c,e[0].charAt(0)+b):a.replace("?","?"+b+"&")}
function df(a){var b=Te();if(b){var c=y(a);for(a=c.next();!a.done;a=c.next()){var d=a.value.data;if(d&&$c(d,ud,8)&&(a=Q(d,ud,8),a=S(a,4))){c=b.fetchAppStoreOverlay;d=Q(d,ud,8);d=S(d,6);c.call(b,a,void 0,d);break}}}}
function ef(a,b){function c(g,k){if(k){g=y(e);for(var l=g.next();!l.done;l=g.next())l=l.value,k[l.J()]&&l.aa(!0)}}b=b===void 0?500:b;var d=[],e=[];a=y(a);for(var h=a.next();!h.done;h=a.next())(h=h.value.data)&&$c(h,X,12)&&(e.push(Q(h,X,12)),d.push(Q(h,X,12).J()));a=Te();d=y(d);for(h=d.next();!h.done;h=d.next()){h=h.value;var f=void 0;(f=a)==null||f.canOpenAndroidApp(h,c,function(){},b)}}
function ff(a,b,c,d){function e(w){return d.openStoreOverlay(w,l,m,S(h,6))}if(!b||!$c(b,ud,8))return!1;var h=Q(b,ud,8),f=S(h,2);id(b,10).forEach(function(w,z){f=bf(f,z,w)});gf(b)&&R(b,15)&&!/[?&]label=/.test(c)&&(c=af(c,"label","deep_link_fallback"));(a==null?0:R(a,1))&&Se("skspvc",{});var g=a==null?void 0:R(a,7),k=S(b,9),l=void 0,m=void 0,n=-1;if(g&&k){var p=Ce(k,"skspvc_triggered"),q=Ce(k,"skspvc_registered"),r=Ce(k,"skspvc_dismissed");l=function(){Qd(p);n=setTimeout(function(){Qd(q)},3E3)};m=function(){Qd(r);
clearTimeout(n)}}return d.redirectForStoreU2({clickUrl:c,trackingUrl:S(h,3),finalUrl:f,pingFunc:R(b,13)?d.httpTrack:d.click,openFunc:(a==null?0:R(a,1))?e:d.openIntentOrNativeApp,isExternalClickUrl:R(b,13)})}function hf(a,b,c,d){c&&c.startsWith("intent:")?d.openIntentOrNativeApp(c):a?b?d.openBrowser(c):d.openChromeCustomTab(c):d.openSystemBrowser(c,{useFirstPackage:!0,useRunningProcess:!0})}
function jf(a,b,c){b=b===void 0?null:b;c=c===void 0?1:c;if(b===null)return b=new Ea({url:a,pa:null}),b.g.dsh==="1"||b.g.aspm!=="1"?b=(c=Fa(b,0))?navigator.sendBeacon?navigator.sendBeacon(c.I,"")?c.O:Ha(b,2):Ha(b,0):a:(b=Fa(b,1))?(fetch(b.I,{keepalive:!0,mode:"no-cors",credentials:"include"}),b=b.O):b=a,b;var d=Fa(new Ea({url:a}),0);if(!d)return a;a=d.I;if(d.version===4&&c===2){var e="3";e=e===void 0?"":e;var h=encodeURIComponent("ase"),f=encodeURIComponent(e);h=new RegExp("[?&]"+h+"=([^&]+)","g");
for(var g=0,k=[],l=h.exec(a);l!==null;){if(e.length==0||l[1]==f){var m=l[0].charAt(0)=="?"?1:0;k.push(a.slice(g,l.index+m));g=l.index+l[0].length+m}l=h.exec(a)}k.push(a.slice(g));a=k.join("")}d.version!==3&&c===3&&(a="");b(a);return d.O}function kf(a,b){(b===void 0||b)&&Ue.fetch?Ue.fetch(a,{method:"GET",keepalive:!0,mode:"no-cors"}).then(function(c){c.ok||Od(Ue,a)}):Od(Ue,a)}function af(a,b,c){b=encodeURIComponent(String(b));c=encodeURIComponent(String(c));return a.replace("?","?"+b+"="+c+"&")}
function gf(a){a=y(xd(a));for(var b=a.next();!b.done;b=a.next())if(b=b.value,kd(b,1)===3&&S(b,2))return!0;return!1};function lf(a,b){return a&&(a=a.match(b+"=([^&]+)"))&&a.length==2?a[1]:""};function mf(a){this.i=N(a,void 0,void 0,2048)}x(mf,V);function nf(a){this.i=N(a,void 0,void 0,2048)}x(nf,V);function of(a){this.i=N(a,void 0,void 0,2048)}x(of,V);function pf(a,b){return U(a,2,b)}function qf(a,b){return U(a,3,b)}function rf(a,b){return U(a,4,b)}function sf(a,b){return U(a,5,b)}function vf(a,b){return U(a,9,b)}
function wf(a,b){Wc(a);var c=a.i,d=c[E]|0;if(b==null)P(c,d,10);else{for(var e=b===Bb?7:b[E]|0,h=e,f=gd(e),g=f||Object.isFrozen(b),k=!0,l=!0,m=0;m<b.length;m++){var n=b[m];f||(n=G(n),k&&(k=!n),l&&(l=n))}f||(e=k?13:5,e=l?e&-4097:e|4096);g&&e===h||(b=bc(b),h=0,e=ed(e,d));e!==h&&F(b,e);d=P(c,d,10,b);2&e||!(4096&e||16&e)||Xc(c,d)}return a}function xf(a,b){return ld(a,11,b)}function yf(a,b){return U(a,1,b)}function zf(a,b){return ld(a,7,b)};var Af="platform platformVersion architecture model uaFullVersion bitness fullVersionList wow64".split(" ");function Bf(a){var b;return(b=a.google_tag_data)!=null?b:a.google_tag_data={}}function Cf(a){var b,c;return typeof((b=a.navigator)==null?void 0:(c=b.userAgentData)==null?void 0:c.getHighEntropyValues)==="function"}
function Df(){var a=window;if(!Cf(a))return null;var b=Bf(a);if(b.uach_promise)return b.uach_promise;a=a.navigator.userAgentData.getHighEntropyValues(Af).then(function(c){b.uach!=null||(b.uach=c);return c});return b.uach_promise=a}
function Ef(a){var b;return xf(wf(sf(pf(yf(rf(zf(vf(qf(new of,a.architecture||""),a.bitness||""),a.mobile||!1),a.model||""),a.platform||""),a.platformVersion||""),a.uaFullVersion||""),((b=a.fullVersionList)==null?void 0:b.map(function(c){var d=new nf;d=U(d,1,c.brand);return U(d,2,c.version)}))||[]),a.wow64||!1)}function Ff(){var a,b;return(b=(a=Df())==null?void 0:a.then(function(c){return Ef(c)}))!=null?b:null};function Gf(a){var b=this;this.C=nb||kb||ob||lb;var c=Ve("data-asoch-meta");if(c.length!==1)Se("gdn-asoch",{type:2,data:c.length});else{this.U=70;this.h=new yd(JSON.parse(c[0].getAttribute("data-asoch-meta"))||[]);this.R=a["extra-meta"]?new yd(JSON.parse(a["extra-meta"])):null;this.T=a["is-fsn"]==="true";this.ea=a["is-tap-disabled-for-fsn"]==="true";this.m=a["ios-store-overlay-config"]?new sd(JSON.parse(a["ios-store-overlay-config"])):null;this.ha=a["use-cct-over-browser"]==="true";this.Y=a["correct-redirect-url-for-och-15-click"]===
"true";this.ga=a["spitzer-use-click-url-for-fallback"]==="true";this.H=a["default-msg-in-och"]==="true";this.da=a["enable-paw"]==="true";this.L=a["allow-redirection-muted-in-och"]==="true";this.ca=a["add-spam-signal-before-building-attribution-src-url"]==="true";this.X=a["och-move-sonic-attribution-src-logic"]==="true";this.fa=a.scpsasp==="true";this.M=Number(a["custom-async-tracking-throttle-interval"])||-1;this.o="";c=Ff();c!=null&&c.then(function(e){var h=nd(e);e=[];for(var f=0,g=0;g<h.length;g++){var k=
h.charCodeAt(g);k>255&&(e[f++]=k&255,k>>=8);e[f++]=k}h=3;h===void 0&&(h=0);if(!qb)for(qb={},f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),g=["+/=","+/","-_=","-_.","-_"],k=0;k<5;k++){var l=f.concat(g[k].split(""));pb[k]=l;for(var m=0;m<l.length;m++){var n=l[m];qb[n]===void 0&&(qb[n]=m)}}h=pb[h];f=Array(Math.floor(e.length/3));g=h[64]||"";for(k=l=0;l<e.length-2;l+=3){var p=e[l],q=e[l+1];n=e[l+2];m=h[p>>2];p=h[(p&3)<<4|q>>4];q=h[(q&15)<<2|n>>6];n=h[n&63];f[k++]=m+p+q+
n}m=0;n=g;switch(e.length-l){case 2:m=e[l+1],n=h[(m&15)<<2]||g;case 1:e=e[l],f[k]=h[e>>2]+h[(e&3)<<4|m>>4]+n+g}b.o=f.join("")});this.g=Ze(this.h);this.H&&(this.l=null,hd(this.h,1,wd).forEach(function(e){b.l!=null||K(O(e,2))==null||K(O(e,9))==null||R(e,13)||(b.l=e)}));this.ia=Number(a["deeplink-and-android-app-validation-timeout"])||500;this.V=-Infinity;this.u=this.S=0;this.j=S(this.h,5)||"";this.W=R(this.h,11);this.R&&(this.W=R(this.R,11));this.G=this.K=this.D=this.F=null;R(this.h,3)||(cf(this.g),
ld(this.h,3,!0));Hf(this.g);a=Te();!this.C&&a&&ef(this.g,this.ia);var d;if(a&&((d=this.m)==null?0:R(d,2)))switch(d=function(){var e=jd(b.m,4);e>0?B.setTimeout(function(){df(b.g)},e):df(b.g)},kd(this.m,3)){case 1:a.runOnOnShowEvent(d);break;case 2:Nd(d);break;default:df(this.g)}Kd(Y,"click",Re(557,function(e){If(b,e)}),Gd);Kd(Y,"auxclick",Re(557,function(e){e.button===1&&If(b,e)}),Gd);this.j&&typeof window.ss==="function"&&Kd(Y.body,"mouseover",Re(626,function(){window.ss(b.j,0)}),Hd);typeof window.ivti===
"function"&&window.ivti(Y.body);d=window;d.googqscp&&typeof d.googqscp.registerCallback==="function"&&d.googqscp.registerCallback(function(e,h,f,g){b.F=e;b.G=h;b.D=f;b.K=g});Yd()}}
function If(a,b){if(!b.defaultPrevented||a.F===b){for(var c,d,e=b.target;(!c||!d)&&e;){d||e.tagName!="A"||(d=e);var h=e.hasAttribute("data-asoch-targets"),f=e.hasAttribute("data-asoch-fixed-value");if(!c)if(f)c=new wd(JSON.parse(e.getAttribute("data-asoch-fixed-value"))||[]);else if(e.tagName=="A"||h)if(h=h&&e.getAttribute("data-asoch-is-dynamic")==="true"?Ze(a.h,[e]):a.g,h=Jf(h,e))c=h.data;e=e.parentElement}e=c&&!R(c,1);if(a.H&&a.l&&b.defaultPrevented)Kf(a,b,d,e?c:a.l);else{if(e){if(!a.H&&b.defaultPrevented){Kf(a,
b,d,c);return}h=y(bd(c,6,K,void 0===Kb?2:4));for(f=h.next();!f.done;f=h.next())kf(f.value)}a.L&&e&&R(c,21)&&Ld(b);if(d&&e){c=e?c:null;a.ca?(Lf(a,b,d,c),Mf(a,d,c)):(Mf(a,d,c),Lf(a,b,d,c));e=y(bd(a.h,17,K,void 0===Kb?2:4));for(f=e.next();!f.done;f=e.next()){h=void 0;var g=f.value,k=Y.body;h=h===void 0?{}:h;typeof window.CustomEvent==="function"?f=new CustomEvent(g,h):(f=document.createEvent("CustomEvent"),f.initCustomEvent(g,!!h.bubbles,!!h.cancelable,h.detail));k.dispatchEvent(f)}var l;if(c==null?
0:(l=Q(c,vd,26))==null?0:K(O(l,1))!=null){l=new pd;kc(O(c,5))!=null?(e=kd(c,5),md(l,1,e)):(e=lf(d.href,"nb"),e!=""&&md(l,1,+e));e=lf(d.href,"nx");e!=""&&T(l,2,+e);e=lf(d.href,"ny");e!=""&&T(l,3,+e);e=lf(d.href,"bg");e!=""&&U(l,4,e);e=lf(d.href,"nm");e!=""&&T(l,5,+e);e=lf(d.href,"mb");e!=""&&T(l,6,+e);e=Be(d.href,"bg");Va(d,Oe(e,Pe(1211)));e=Q(c,vd,26);f=S(e,1);e=Q(c,vd,26);e=S(e,2);h=lc(O(c,20))!=null?jd(c,20):null;k=nd(l);l=a.o;g=B;g=g===void 0?window:g;var m=new zd;f=U(m,1,f);f=U(f,4,k);f=U(f,10,
Date.now().toString());h!==null&&T(f,2,h);l!==null&&U(f,3,l);md(f,9,7);var n;g==null||(n=g.fence)==null||n.setReportEventDataForAutomaticBeacons({eventType:"reserved.top_navigation_start",eventData:JSON.stringify(f),destination:["buyer"],once:!0});var p;g==null||(p=g.fence)==null||p.reportEvent({eventType:"click",eventData:e,destination:["component-seller"]})}R(a.h,16)||a.T?Nf(a,b,d,c):(n="",(p=Te())&&(n=p.appendClickSignals(d.href)),Of(a,b,d,c,n))}}}}
function Kf(a,b,c,d){if(a.F===b&&a.G){var e=new rd(a.G),h=S(d,9),f="";switch(kd(e,4,1)){case 2:if(jd(e,2))f="blocked_fast_click";else if(S(e,1)||S(e,7))f="blocked_border_click";break;case 3:var g=g===void 0?Y:g;f=g.getElementById?g.getElementById("common_15click_anchor"):null;g=window;if(typeof g.copfcChm==="function"&&f){var k=Uc(d);md(k,5,12);id(k,4).set("nb",(12).toString());var l=Jf(a.g,f);l?l.data=k:a.g.push({element:f,data:k});!a.Y&&c&&(Lf(a,b,c,k),U(k,2,c.href));g.copfcChm(b,Ye(k,f.href),null,
$c(e,qd,10)?nd(Q(e,qd,10)):null);a.Y&&Lf(a,b,f,k)}f="onepointfiveclick_first_click"}h&&f&&(c=h+"&label="+f,f==="onepointfiveclick_first_click"&&(e=kd(d,5),a.fa?(d=new mf,h=b.clientX,h=h==null?h:mc(h),Zc(d,1,h),b=b.clientY,b=b==null?b:mc(b),Zc(d,2,b),T(d,3,e),b=a.D?a.D.changedTouches:[],e=a.K?a.K.changedTouches:[],b&&e&&b.length>0&&e.length>0&&(T(d,4,b[0].clientX),T(d,5,b[0].clientY),T(d,6,e[0].clientX),T(d,7,e[0].clientY)),c+="&cpspb="+nd(d)):c+="&ccx="+b.clientX+"&ccy="+b.clientY+"&ccnb="+e),kf(c,
!1));ae(a.U)}}function Mf(a,b,c){var d=Jf(a.g,b);d?d=d.data:(d=new wd,U(d,2,b.href),U(d,11,b.target||"_top"),a.g.push({element:b,data:d}));$e(b,c||d,S(d,2),557,a.X)}
function Nf(a,b,c,d){var e,h,f;wa(new va(new ra(function(g){switch(g.g){case 1:e="";h=Te();if(!h){g.g=2;break}b.preventDefault();var k=h.appendClickSignalsAsync(c.href);g.g=3;return{value:k};case 3:e=g.m||"";if(!a.T){g.g=2;break}a.ea?g=g.return():(k=h.getNativeClickMeta(),g.g=5,g={value:k});return g;case 5:if(f=g.m){if(f.customClickGestureEligible)return g.return();e=af(e,"nas",f.encodedNas)}case 2:Of(a,b,c,d,e),g.g=0}})))}
function Of(a,b,c,d,e){a.S++;a.u<0&&(a.u=Date.now());var h=R(a.h,2),f=a.M>0?a.M:300,g=h&&Date.now()-a.V>f,k=Te();if(k)Ld(b),function(){var m=R(d,13)?e:k.logScionEventAndAddParam(e);if(!a.C&&d&&$c(d,X,12)){var n=Q(d,X,12).J();var p="";if(xd(d).length>0)for(var q=y(xd(d)),r=q.next();!r.done;r=q.next())r=r.value,p+=S(r,2)+" "+r.J()+" ";p=Q(d,X,12);R(p,2)?(k.click(m),k.openAndroidApp(n),n=!0):n=!1}else n=!1;if(!n&&!ff(a.m,d,m,k))a:{n=a.ha;p=a.C;q=a.L;r=a.ga;q=q===void 0?!1:q;r=r===void 0?!1:r;var w=R(d,
15);if(!r&&w&&K(O(d,22))!=null)hf(n,p,S(d,22),k);else{var z=Fa(new Ea({url:m}),0);r=w&&(z&&z.version===3||r);if(h&&g&&!r&&(m=jf(m,k.click,2),q&&(d==null?0:R(d,21))))break a;hf(n,p,m,k)}}}();else if(b=window,a.da&&b.pawsig&&typeof b.pawsig.clk==="function")Se("paw_sigs",{msg:"click",count:a.S.toString(),elapsed:(Date.now()-a.u).toString()}),g&&b.pawsig.clk(c);else if(g){b=c.getAttribute("attributionsrc")!=null&&ze(c.getAttribute("attributionsrc"),"nis")==="6";f="";var l;f=a.X&&c.getAttribute("attributionsrc")!=
null&&((l=Y.featurePolicy)==null?0:l.allowedFeatures().includes("attribution-reporting"))?jf(c.href,function(m){c.setAttribute("attributionsrc",m)},3):b?jf(c.href,function(){}):jf(c.href);f!==c.href&&Va(c,Oe(f,Pe(599)))}g&&(a.V=Date.now());ae(a.U)}
function Lf(a,b,c,d){if(!R(d,13)){var e=c.href;var h=/[?&]adurl=([^&]+)/.exec(e);e=h?[e.slice(0,h.index),e.slice(h.index)]:[e,""];for(Va(c,Oe(e[0],Pe(557)));!c.id;)if(h="asoch-id-"+(Math.floor(Math.random()*2147483648).toString(36)+Math.abs(Math.floor(Math.random()*2147483648)^Date.now()).toString(36)),!Y.getElementById(h)){c.id=h;break}h=c.id;typeof window.xy==="function"&&window.xy(b,c,Y.body);typeof window.mb==="function"&&window.mb(c);typeof window.bgz==="function"&&window.bgz(h);typeof window.ja===
"function"&&window.ja(h,d?kd(d,5):0);typeof window.vti==="function"&&window.vti(c);a.j&&typeof window.ss==="function"&&(a.W?window.ss(h,1,a.j):window.ss(a.j,1));if(e.length>0){var f;b=a.o.length>0&&(d==null||(f=Q(d,vd,26))==null||K(O(f,1))==null)?c.href+"&uach="+encodeURIComponent(a.o)+e[1]:c.href+e[1];Va(c,Oe(b,Pe(557)))}}}function Pf(a){Md(Re(556,function(){new Gf(a||{})}))}function Jf(a,b){return Ya(a,function(c){return c.element===b})}
function Hf(a){a=y(a);for(var b=a.next();!b.done;b=a.next()){var c=b.value;c.element.tagName=="A"&&(b=c.element,c=c.data,K(O(c,2))!=null||U(c,2,b.href))}};var Qf=Re(555,function(a){return Pf(a)});Rd=70;var Rf=Zd(70,document.currentScript);if(Rf==null)throw Error("JSC not found 70");for(var Sf={},Tf=Rf.attributes,Uf=Tf.length-1;Uf>=0;Uf--){var Vf=Tf[Uf].name;Vf.indexOf("data-jcp-")===0&&(Sf[Vf.substring(9)]=Tf[Uf].value)}Qf(Sf);}).call(this);
